#!/bin/bash

echo "BUILD CONF FILES";
FILENAME_I=$DIR_APP_DOCKER$DIR_APP_PROPERTIES_TEMPLATES"/template_memo.properties";
FILENAME_O=$DIR_APP_DOCKER$DIR_APP_PROPERTIES"/memo.properties";
# memo.properties
if [ -f $FILENAME_I ] && [ -f $FILENAME_O ]
then
	echo "SET $FILENAME_I";
	FILE=`cat $FILENAME_I`; 
	FILE=${FILE/@ENV/$ENV};
	FILE=${FILE/@JOBS_MAILS/$JOBS_MAILS};
	FILE=${FILE/@JOBS_ADMINS/$JOBS_ADMINS};
	FILE=${FILE/@JOBS_CALCULS/$JOBS_CALCULS};
	FILE=${FILE/@PATH_CSV_EXPORT/$PATH_CSV_EXPORT};
	FILE=${FILE/@IPS_CONSEILLER/$IPS_CONSEILLER};
	
	echo "$FILE" > $FILENAME_O;
else
	echo $FILENAME_I " ou " $FILENAME_O " n'existe pas";

fi
FILENAME_I=$DIR_APP_DOCKER$DIR_APP_PROPERTIES_TEMPLATES"/template_mails.properties";
FILENAME_O=$DIR_APP_DOCKER$DIR_APP_PROPERTIES"/mails.properties";
# mails.properties
if [ -f $FILENAME_I ] && [ -f $FILENAME_O ]
then
	echo "SET $FILENAME_I";
	FILE=`cat $FILENAME_I`; 
	FILE=${FILE/@EMAIL_NOREPLY/$EMAIL_NOREPLY};
	FILE=${FILE/@EMAIL_NOREPLYEXT/$EMAIL_NOREPLYEXT};
	FILE=${FILE/@EMAIL_INTRAS/$EMAIL_INTRAS};
	FILE=${FILE/@EMAIL_DEVS/$EMAIL_DEVS};
	FILE=${FILE/@EMAIL_EXTRAS/$EMAIL_EXTRAS};
	FILE=${FILE/@HOST_POSTFIX/$HOST_POSTFIX};
	FILE=${FILE/@HOST_HELO/$HOST_HELO};
	FILE=${FILE/@URL_MEMO/$URL_MEMO};
	FILE=${FILE/@PATH_LOGO_MEMO/$PATH_LOGO_MEMO};
	FILE=${FILE/@PATH_LOGO_PE/$PATH_LOGO_PE};
	echo "$FILE" > $FILENAME_O;
else
	echo $FILENAME_I " ou " $FILENAME_O " n'existe pas";

fi

# context.xml
FILENAME_I=$DIR_APP_DOCKER$DIR_APP_DATASOURCE"/template_context.xml";
FILENAME_O=$DIR_APP_DOCKER$DIR_APP_DATASOURCE"/context.xml";
if [ -f $FILENAME_I ] && [ -f $FILENAME_O ]
then
	echo "SET $FILENAME_I";
	FILE=`cat $FILENAME_I`; 
	FILE=${FILE/@DB_DOCKER_HOST/$DB_DOCKER_HOST};
	FILE=${FILE/@DB_DOCKER_HOST_CALCUL/$DB_DOCKER_HOST_CALCUL};
	FILE=${FILE//@DB_USER_NAME/$DB_USER_NAME};
	FILE=${FILE//@DB_USER_PASS/$DB_USER_PASS};
	FILE=${FILE/@DB_USER_NAME_REPLI/$DB_USER_NAME_REPLI};
	FILE=${FILE/@DB_USER_PASS_REPLI/$DB_USER_PASS_REPLI};
	FILE=${FILE//@DB_PORT/$DB_PORT};
	FILE=${FILE//@DB_NAME/$DB_NAME};
	echo "$FILE" > $FILENAME_O;
else
	echo $FILENAME_I " ou " $FILENAME_O " n'existe pas";
fi

# secret.properties
FILENAME_I=$DIR_APP_DOCKER$DIR_APP_PROPERTIES_TEMPLATES"/template_secret.properties";
FILENAME_O=$DIR_APP_DOCKER$DIR_APP_PROPERTIES"/secret.properties";
if [ -f $FILENAME_I ] && [ -f $FILENAME_O ]
then
	echo "SET $FILENAME_I";
	FILE=`cat $FILENAME_I`; 
	FILE=${FILE/@SALT/$SALT};
	FILE=${FILE/@ENCRYPTOR/$ENCRYPTOR};
	FILE=${FILE/@ALGO/$ALGO};
	FILE=${FILE/@PWD_SQL_2/$PWD_SQL_2};
	FILE=${FILE/@PWD_SQL/$PWD_SQL};
	FILE=${FILE/@LBB_SECRET/$LBB_SECRET};
	FILE=${FILE/@CLIENT_ID/$CLIENT_ID};
	FILE=${FILE/@CLIENT_SECRET/$CLIENT_SECRET};
	FILE=${FILE/@API_MEMO_KEY/$API_MEMO_KEY};
	FILE=${FILE/@API_MEMO_ALGO/$API_MEMO_ALGO};
	echo "$FILE" > $FILENAME_O;
else
	echo $FILENAME_I " ou " $FILENAME_O " n'existe pas";
fi

# api.properties
FILENAME_I=$DIR_APP_DOCKER$DIR_APP_PROPERTIES_TEMPLATES"/template_api.properties";
FILENAME_O=$DIR_APP_DOCKER$DIR_APP_PROPERTIES"/api.properties";
if [ -f $FILENAME_I ] && [ -f $FILENAME_O ]
then
	echo "SET $FILENAME_I";
	FILE=`cat $FILENAME_I`;
	FILE=${FILE/@ACCESS_TOKEN_PE_CONNECT/$ACCESS_TOKEN_PE_CONNECT};
	FILE=${FILE/@URL_MEMO/$URL_MEMO};
	FILE=${FILE/@API_USER_SAVE_CANDIDATURE/$API_USER_SAVE_CANDIDATURE};
	FILE=${FILE/@API_LBB_FICHE_URL/$API_LBB_FICHE_URL};
	echo "$FILE" > $FILENAME_O;
else
	echo $FILENAME_I " ou " $FILENAME_O " n'existe pas";
fi

# datalake.properties
FILENAME_I=$DIR_APP_DOCKER$DIR_APP_PROPERTIES_TEMPLATES"/template_datalake.properties";
FILENAME_O=$DIR_APP_DOCKER$DIR_APP_PROPERTIES"/datalake.properties";
if [ -f $FILENAME_I ] && [ -f $FILENAME_O ]
then
	echo "SET $FILENAME_I";
	FILE=`cat $FILENAME_I`;
	FILE=${FILE/@PATH_EXPORT_DATALAKE_JSON/$PATH_EXPORT_DATALAKE_JSON};
	echo "$FILE" > $FILENAME_O;
else
	echo $FILENAME_I " ou " $FILENAME_O " n'existe pas";
fi    

# reporting.properties
FILENAME_I=$DIR_APP_DOCKER$DIR_APP_PROPERTIES_TEMPLATES"/template_reporting.properties";
FILENAME_O=$DIR_APP_DOCKER$DIR_APP_PROPERTIES"/reporting.properties";
if [ -f $FILENAME_I ] && [ -f $FILENAME_O ]
then
	echo "SET $FILENAME_I";
	FILE=`cat $FILENAME_I`;
	FILE=${FILE/@METRICS_PROD/$METRICS_PROD};
	FILE=${FILE/@METRICS_RE7/$METRICS_RE7};
	echo "$FILE" > $FILENAME_O;
else
	echo $FILENAME_I " ou " $FILENAME_O " n'existe pas";
fi

# slack.properties
FILENAME_I=$DIR_APP_DOCKER$DIR_APP_PROPERTIES_TEMPLATES"/template_slack.properties";
FILENAME_O=$DIR_APP_DOCKER$DIR_APP_PROPERTIES"/slack.properties";
if [ -f $FILENAME_I ] && [ -f $FILENAME_O ]
then
	echo "SET $FILENAME_I";
	FILE=`cat $FILENAME_I`;
	FILE=${FILE/@URL_SLACK/$URL_SLACK};
	echo "$FILE" > $FILENAME_O;
else
	echo $FILENAME_I " ou " $FILENAME_O " n'existe pas";
fi
